### ISSUE TITLE
Membrane voltage offset parameter

### ISSUE THREAD

**Issue by stevemonaco** [swharden/HHSharp#1]
Hi,

I created a HH model heavily based upon your HHModel and came across a simple issue that took me awhile to troubleshoot: The membrane voltage is adjusted outside of the model in the simulators (ie. -70 mV). I expected that HHModel would be wholly sufficient to reproduce your screenshots, but this was not the case. Would you please consider this small design change for others who are writing HH so they can avoid the same stumble?

**Comment by swharden** [comment]
Hi @stevemonaco, I'm happy you found the HH model useful! Thanks for noting how this topic was confusing. Redefining your concern, the the HH model is centered at 0 mV but in the applications and screenshots in this project voltage appears to be centered around -70 mV. 

A -70 mV offset is applied by the graphing library (not the HH model):

https://github.com/swharden/HHSharp/blob/b8ad742f9cd16cff2cf2e815ec0dd7444df84bf3/src/HHSharp/FormSim.cs#L118

https://github.com/swharden/HHSharp/blob/b8ad742f9cd16cff2cf2e815ec0dd7444df84bf3/src/HHSharp/FormLive.cs#L29

One option would be to add an optional voltage offset parameter in the HHModel constructor, then convert `Vm` from a class-level variable to a property which returns the voltage plus the offset... but this seems like a lot of added complexity...

Perhaps a simpler option is to add a getter method that can apply the offset:

```cs
public double GetVoltage(double offset = -70) { return Vm + offset; }
```

... then refactor the demos to get voltage this way

@stevemonaco what do you think of this option?

**Comment by stevemonaco** [comment]
Either approach is sufficient given that it happens within the model.

My personal model changed Vm to a private property and added MembraneVoltage and VoltageOffset (or V0) as public properties. Then do the addition as a final step in the solver (HHModel.UpdateCurrentsAndVoltage() in your project).

But I don't have a strong opinion on either approach. You may wish to use the method approach if it makes sense to keep documentation more in-line with the original paper.
